package Pojos;
// Generated 23 ene. 2025 9:28:11 by Hibernate Tools 4.3.1


import javax.persistence.*;

import org.hibernate.annotations.GenericGenerator;

import java.util.ArrayList;
import java.util.Collection;

/**
 * Departamento generated by hbm2java
 */
@Entity
@Table(name="DEPARTAMENTO"
    ,schema="dbo"
    ,catalog="EmpresaHB"
    , uniqueConstraints = @UniqueConstraint(columnNames="Nome_departamento") 
)
public class Departamento  implements java.io.Serializable {


     private int numDepartamento;
     private String nomeDepartamento;

     private Collection<String> lugares = new ArrayList<>();

    public Departamento() {
    }

    public Departamento(int numDepartamento, String nomeDepartamento) {
       this.numDepartamento = numDepartamento;
       this.nomeDepartamento = nomeDepartamento;
    }
   
    @Id 
    @Column(name="Num_departamento", unique=true, nullable=false)
    @GeneratedValue(generator = "increment")
    @GenericGenerator(name = "increment", strategy = "increment")
    
    public int getNumDepartamento() {
        return this.numDepartamento;
    }

    public Departamento(String nomeDepartamento) {
        this.nomeDepartamento = nomeDepartamento;
    }
    
    public void setNumDepartamento(int numDepartamento) {
        this.numDepartamento = numDepartamento;
    }

    
    @Column(name="Nome_departamento", unique=true, nullable=false, length=25)
    public String getNomeDepartamento() {
        return this.nomeDepartamento;
    }
    
    public void setNomeDepartamento(String nomeDepartamento) {
        this.nomeDepartamento = nomeDepartamento;
    }

    /*mapeo de los lugares como componentes*/
    @ElementCollection
    @CollectionTable(name = "LUGAR", joinColumns = @JoinColumn(name = "numDepartamento"))
    @Column(name = "lugar", length = 15)
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    public Collection<String> getLugares() {
        return lugares;
    }

    public void setLugares(Collection<String> lugares) {
        this.lugares = lugares;
    }
}


