package Pojos;
// Generated 23 ene. 2025 9:28:11 by Hibernate Tools 4.3.1


import Pojos.Familiar;
import Pojos.Telefono;
import org.hibernate.annotations.ListIndexBase;

import java.util.*;
import javax.persistence.*;

/**
 * Empregado generated by hbm2java
 */
@Entity
@Table(name="EMPREGADO"
    ,schema="dbo"
    ,catalog="EmpresaHB"
)
public class Empregado  implements java.io.Serializable {


     private String nss;
     private String nome;
     private String apelido1;
     private String apelido2;
     private Double salario;
     private Date dataNacemento;
     private Character sexo;
     //private Set<String> telefonos;
     //private Set<Telefono> telefonos = new HashSet<>();
    private Map<String, String> telefonos = new HashMap<>();


    List<Familiar> familiares = new ArrayList<>();

    @ElementCollection
    @CollectionTable(name = "FAMILIAR", joinColumns = @JoinColumn(name = "NSS_Empregado"))
    //@OrderColumn(name = "numero")
    @ListIndexBase(1)
    public List<Familiar> getFamiliares() {
        return familiares;
    }

    public void setFamiliares(List<Familiar> familiares) {
        this.familiares = familiares;
    }

    @ElementCollection
    @CollectionTable(name = "TELEFONO", joinColumns = @JoinColumn(name = "NSSEmpregado"))
    @MapKeyColumn(name = "Numero")
    @Column(name = "Informacion", nullable = true)
    public Map<String, String> getTelefonos() {
        return telefonos;
    }

    public void setTelefonos(Map<String, String> telefonos) {
        this.telefonos = telefonos;
    }

    Collection<String> aficciones = new ArrayList<>();

    @ElementCollection
    @CollectionTable(name = "AFICCION", joinColumns = @JoinColumn(name = "NSSEmpregado"))
    @Column(name = "Aficcion", nullable = false)
    public Collection<String> getAficciones() {
        return aficciones;
    }

    public void setAficciones(Collection<String> aficciones) {
        this.aficciones = aficciones;
    }

    //Mapeo de la coleccion de telefonos con solo telefono como componente
     /*@ElementCollection
     @CollectionTable(name = "TELEFONO", joinColumns = @JoinColumn(name = "NSSEmpregado"))
     @Column(name = "Numero")*/


    /*@ElementCollection //telefono es componente
    @CollectionTable(name = "TELEFONO",joinColumns = @JoinColumn(name = "NSSEmpregado"))
    public Set<Telefono> getTelefonos() {
        return telefonos;
    }



    public void setTelefonos(Set<Telefono> telefonos) {
        this.telefonos = telefonos;
    }

    public Set<String> getTelefonos() {
        return telefonos;
    }

    public void setTelefonos(Set<String> telefonos) {
        this.telefonos = telefonos;
    }*/
     
    public Empregado() {
    }

	
    public Empregado(String nss, String nome, String apelido1) {
        this.nss = nss;
        this.nome = nome;
        this.apelido1 = apelido1;
    }
    public Empregado(String nss, String nome, String apelido1, String apelido2, Double salario, Date dataNacemento, Character sexo) {
       this.nss = nss;
       this.nome = nome;
       this.apelido1 = apelido1;
       this.apelido2 = apelido2;
       this.salario = salario;
       this.dataNacemento = dataNacemento;
       this.sexo = sexo;
    }
   
     @Id 

    
    @Column(name="NSS", unique=true, nullable=false, length=15)
    public String getNss() {
        return this.nss;
    }
    
    public void setNss(String nss) {
        this.nss = nss;
    }

    
    @Column(name="Nome", nullable=false, length=25)
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }

    
    @Column(name="Apelido_1", nullable=false, length=25)
    public String getApelido1() {
        return this.apelido1;
    }
    
    public void setApelido1(String apelido1) {
        this.apelido1 = apelido1;
    }

    
    @Column(name="Apelido_2", length=25)
    public String getApelido2() {
        return this.apelido2;
    }
    
    public void setApelido2(String apelido2) {
        this.apelido2 = apelido2;
    }

    
    @Column(name="Salario", precision=53, scale=0)
    public Double getSalario() {
        return this.salario;
    }
    
    public void setSalario(Double salario) {
        this.salario = salario;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="Data_nacemento", length=10)
    public Date getDataNacemento() {
        return this.dataNacemento;
    }
    
    public void setDataNacemento(Date dataNacemento) {
        this.dataNacemento = dataNacemento;
    }

    
    @Column(name="Sexo", length=1)
    public Character getSexo() {
        return this.sexo;
    }
    
    public void setSexo(Character sexo) {
        this.sexo = sexo;
    }

}


